backend:
  name: github
  repo: engfawazmohammednasser-cmyk/Aden-Server-for-Technologies # مسار مستودعك بالضبط
  branch: main # الفرع الرئيسي للموقع

media_folder: "images" # المجلد الذي تُحفظ فيه صور المنتجات الجديدة
public_folder: "images"

collections:
  - name: "products"
    label: "المنتجات والعروض"
    folder: "data/products" # سيقوم النظام بإنشاء مجلد هنا لحفظ بيانات المنتجات
    create: true # السماح للآدمن بإضافة منتجات جديدة
    slug: "{{slug}}"
    fields:
      - { label: "اسم المنتج أو الباقة", name: "title", widget: "string" }
      - { label: "السعر بالريال", name: "price", widget: "string" }
      - { label: "صورة المنتج", name: "image", widget: "image" }
      - { label: "وصف ومواصفات المنتج", name: "body", widget: "markdown" }