backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "store"
    label: "إدارة المتجر"
    delete: false # لمنع حذف الملف بالكامل بالخطأ
    files:
      - file: "data/products.json" # هنا سيتم حفظ كل المنتجات في ملف واحد فقط!
        label: "قائمة المنتجات"
        name: "products"
        fields:
          - label: "المنتجات"
            name: "items"
            widget: "list" # يسمح لك بإضافة قائمة غير منتهية من المنتجات
            fields:
              - { label: "اسم المنتج", name: "title", widget: "string" }
              - { label: "السعر", name: "price", widget: "number" }
              - { label: "صورة المنتج", name: "image", widget: "image" }
              - { label: "وصف المنتج", name: "body", widget: "markdown" }